// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg_PxtcHR3JGWsClYLAx1I8uzDIRvivVU',
    appId: '1:438207784863:web:b53c9a4bf594e06a8c3faa',
    messagingSenderId: '438207784863',
    projectId: 'student-directory-b6447',
    authDomain: 'student-directory-b6447.firebaseapp.com',
    storageBucket: 'student-directory-b6447.firebasestorage.app',
    measurementId: 'G-EZ48CTZ339',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcmEap90BNzBz5iMyG2agux88bzKdkDIs',
    appId: '1:438207784863:android:ec8a68d6b1c12a038c3faa',
    messagingSenderId: '438207784863',
    projectId: 'student-directory-b6447',
    storageBucket: 'student-directory-b6447.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSGAOBinZALPdSB8cTg14opxAetTmX5UA',
    appId: '1:438207784863:ios:df3e57c06444a6918c3faa',
    messagingSenderId: '438207784863',
    projectId: 'student-directory-b6447',
    storageBucket: 'student-directory-b6447.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSGAOBinZALPdSB8cTg14opxAetTmX5UA',
    appId: '1:438207784863:ios:df3e57c06444a6918c3faa',
    messagingSenderId: '438207784863',
    projectId: 'student-directory-b6447',
    storageBucket: 'student-directory-b6447.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg_PxtcHR3JGWsClYLAx1I8uzDIRvivVU',
    appId: '1:438207784863:web:3af1c8d8ca2dff7c8c3faa',
    messagingSenderId: '438207784863',
    projectId: 'student-directory-b6447',
    authDomain: 'student-directory-b6447.firebaseapp.com',
    storageBucket: 'student-directory-b6447.firebasestorage.app',
    measurementId: 'G-N5W07DLCVC',
  );
}
